# Configuration file for both server and clients
# Let's start with the server first
serialport: '/dev/ttyACM' # It will also test ACM1/ACM0 if this doesn't work
camtype: picamera # picamera or opencv
video_id: 0
video_size: [480, 640] #[80, 80] #[640, 480] #[150, 150]
client: ledclient
server_host: '0.0.0.0'
server_ip: http://10.99.39.174:5000
objective_na: 0.16
pupil_size: 11 # Function of NA, wavelength video size and magnification
wavelength: 650E-9
pixelsize: 650E-9
color: red
theta: [0, 360, 10] # [min, max, step]
phi: [0, 17, 2] # [min, max, step]
# theta: [0, 200, 10] # [min, max, step]
# phi: [59, 76, 1] # [min, max, step]
shift: [0, 400, 1]
shift_step: 0.0193 # mm/step [MS1 MS2 MS3] = [1 1 0]
theta_spr: 200
shift_max: 1400 # max steps to border
sample_height: 62 # mm above led
servo_init: 59 # Zero angle for the servo motor
# For the recosntruction
n_iter: 1000 # Max number of iterations
# posible defects
platform_tilt: [0, 0] #[spherical theta, shperical phi]
source_center: [0, 0] #[xcoord, ycoord] of the calibrated center
source_tilt: [0, 0] #[spherical theta, shperical phi]
# The client side of the equation
sweep: radial # The other is neopixels, have to change that name
task: simulation
action: reconstruct
servertype: sampling # simulation or sampling
output_cal: ./out/calibration_20170302.npy
output_sample: ./out_sampling/2017-03-02_03.npy
output_sim: ./output_sim/2017-03-02_03.npy
input_mag: './imgs/mag1.png' # If task is simulation
input_phase: './imgs/phase1.png' # If task is simulation
model_file: ./out/model_20170302.yaml
debug: False # Show me images and be verbose
