# Configuration file for both server and clients
# Let's start with the server first
serialport: '/dev/ttyACM' # It will also test ACM1/ACM0 if this doesn't work
video_id: 0
video_size: [640, 480]
client: ledclient
server_host: '0.0.0.0'
server_ip: 10.99.39.174:5000/acquire
objective_na: 0.6
pupil_size: 60 # Function of NA, wavelength video size and magnification
wavelength: 500E-9
pixelsize: 500E-9
color: red
theta: [0, 180, 10] # [min, max, step]
phi: [0, 30, 5] # [min, max, step]
shift: [0, 400, 1]
shift_step: 0.0193 # mm/step [MS1 MS2 MS3] = [1 1 0]
theta_spr: 200
shift_max: 1400 # max steps to border
sample_height: 62 # mm above led
servo_init: 60 # Zero angle for the servo motor
# posible defects
platform_tilt: [0, 0] #[spherical theta, shperical phi]
source_center: [0, 0] #[xcoord, ycoord] of the calibrated center
source_tilt: [0, 0] #[spherical theta, shperical phi]
# The client side of the equation
sweep: radial
task: simulation
action: reconstruct
servertype: sampling # simulation or sampling
output_cal: ./out/calibration_20170224.npy
output_file: ./out_sampling/2017-02-25.npy
input_mag: './imgs/mag1.png' # If task is simulation
input_phase: './imgs/phase1.png' # If task is simulation
model_file: ./out/model.yaml
debug: False # Show me images and be verbose
