# Configuration file for both server and clients
# Let's start with the server first
serialport: '/dev/ttyACM0' # It will also test ACM1/ACM0 if this doesn't work
camtype:  picamera # picamera or opencv or test
video_id: 0
video_size: [480, 640] #[240, 324] # [150, 150] #[346, 540] #[150, 150] #[480, 648] #[1944, 2592] #[375, 500] #[120, 120] #[346, 540] #[80, 80] #[150, 150]
patch_size: [50, 50]
client: ledclient
server_host: '0.0.0.0'
server_ip: http://10.99.39.174:5000 #http://0.0.0.0:5000 #http://10.99.39.174:5000
objective_na: 0.6 #0.12
na: 0.6
pupil_size: 500 # Function of NA, wavelength video size and magnification
wavelength: 450E-9
#magnification: 8
pixel_size: 0.5E-6 #2.15E-6 #5.67E-6
color: red
theta: [0, 360, 20] # [min, max, step]
phi: [0, 15, 1] # [min, max, step]
phi_max_err: 0 # When corrected, phi max could be larger than specified
max_power: 255
# theta: [0, 200, 10] # [min, max, step]
# phi: [59, 76, 1] # [min, max, step]
shift: [0, 24, 2]
shift_step: 0.0188 # 0.0193 # mm/step [MS1 MS2 MS3] = [1 1 0]
theta_spr: 7680
shift_max: 1800 # max steps to border
sample_height: 106 # mm above led
servo_init: 75 # Zero angle for the servo motor
phi_spr: 2048
# For the recosntruction
n_iter: 50 # Max number of iterations
# possible defects
platform_tilt: [0, 0] #[0, 2.1] #[spherical theta, spherical phi] [0, 2.1]
source_center: [0, 0] #[0, 1.9] #[xcoord, ycoord] of the calibrated center [0, 1.9]
source_tilt: [0, 0] #[spherical theta, sperical phi]
# The client side of the equation
sweep: radial_efficient_shift #radial_efficient #neopixels
task: simulation
action: reconstruct
servertype: sampling # simulation or sampling
output_cal: ./etc/calibration_20170302.npy
output_sample: ./out_sampling/
output_sim: ./out_simulation/
input_mag: '/home/lec/pyfpm/imgs/pinhole_30um_mag.png' # If task is simulation
input_phase: '/home/lec/pyfpm/imgs/pinhole_30um_phase.png' # If task is simulation
model_name: model_2017-03-06_01.yaml #./out/model_20170302.yaml
plat_model: nomodel #nomodel #normal
debug: False # Show me images and be verbose
